//LER IDADE, A IDADE TEM QUE SER MAIOR QUE ZERO, 
//ENQUANTO ESTA CONDIÇÃO FOR VERDADE CONTINUE EXECULTANDO O PROGRAMA, 
//SE A IDADE FOR MAIOR OU IGUAL A 18
//IMPRIMIR "MAIOR DE IDADE SENAO IMPRIMIR MENOR DE IDADE.
Program UM ;

 VAR IDADE: INTEGER;
 
 Begin
   WRITELN ('INFORME IDADE');
   READLN (IDADE);
   WHILE ((IDADE >0) AND (IDADE <100)) DO;
        BEGIN
           IF (IDADE >=18) THEN
              WRITELN ('MAIOR DE IDADE')
           ELSE
              WRITE ('MENOR DE IDADE');
                WRITELN ('INFORME IDADE');
                READLN (IDADE);
        END;
 End.
